INSERT INTO EX.Person (FIRSTNAME, LASTNAME) VALUES ('PAWEL', 'DUDEK')
INSERT INTO EX.Person (FIRSTNAME, LASTNAME) VALUES ('MILENA', 'WOZNIAK')

INSERT INTO EX.Country (NAME, CAPITAL, CURRENCY, POPULATION) VALUES ('Spain', 'Madrid', 'EUR', 46704314)
INSERT INTO EX.Country (NAME, CAPITAL, CURRENCY, POPULATION) VALUES ('Poland', 'Warsow', 'PLN', 40000000)